interface AudioEffectGroupDevice {}
interface Amp {}
interface AutoFilter {}
interface AutoPan {}
interface BeatRepeat {}
interface Cabinet {}
interface ChannelEq {}
interface Chorus {}
interface Compressor2 {}
interface Corpus {}
interface Delay {}
interface DrumBuss {}
interface Tube {}
interface Echo {}
interface Eq8 {}
interface FilterEQ3 {}
interface Erosion {}
interface ProxyAudioEffectDevice {}
interface FilterDelay {}
interface Flanger {}
interface FrequencyShifter {}
interface Gate {}
interface GlueCompressor {}
interface GrainDelay {}
interface Limiter {}
interface Looper {}
interface MultibandDynamics {}
interface Overdrive {}
interface Pedal {}
interface Phaser {}
interface Redux {}
interface Resonator {}
interface Reverb {}
interface Saturator {}
interface SpectrumAnalyzer {}
interface Tuner {}
interface StereoGain {}
interface Vinyl {}
interface Vocoder {}
