export const listOfFeatures = [
  "music",
  "vinyl",
  "merchandise",
  "collectibles",
  "tracks download",
  "mixes download",
  "loops",
  "project files",
  "plug-ins",
  "streaming",
  "booking",
  "chat",
  "social",
];
